version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: examuser
      POSTGRES_PASSWORD: exampass
      POSTGRES_DB: examdb
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    environment:
      DB_HOST: db
      DB_USER: examuser
      DB_PASS: exampass
      DB_NAME: examdb
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    image: nginx:latest
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - backend